  COHP#    atomMU    atomNU   distance   translation   ICOHP (at) eF    ICOHP (at) eF 
                                                          for spin 1       for spin 2 
      1      Co21      O347    1.74323     0   0   0        -1.05645         -2.33612 
      2      Co23      O259    2.04312     0   0   0        -0.52013         -0.86941 
      3      O259      H116    0.97545     0   0   0        -3.87521         -3.90404 
      4      Co21      O258    2.06996     0   0   0        -0.61525         -0.81379 
      5      Co23      O258    2.11233     0   0   0        -0.44612         -0.72457 