  COHP#    atomMU    atomNU   distance   translation   ICOHP (at) eF    ICOHP (at) eF 
                                                          for spin 1       for spin 2 
      1      Co16      O347    1.74323     0   0   0        -0.66391         -2.37854 
      2      Al51      O259    2.04312     0   0   0        -1.97659         -1.99903 
      3      O259      H116    0.97545     0   0   0        -3.87553         -3.90866 
      4      Co16      O258    2.06996     0   0   0        -0.45384         -0.72600 
      5      Al51      O258    2.11233     0   0   0        -1.79013         -1.80602 