  COHP#    atomMU    atomNU   distance   translation   ICOHP (at) eF    ICOHP (at) eF 
                                                          for spin 1       for spin 2 
      1      Co21      O348    1.87588     0   0   0        -0.49618         -1.43149 
      2      Co23      O260    2.04312     0   0   0        -0.51714         -0.86249 
      3      O260      H116    0.97545     0   0   0        -3.86344         -3.88993 
      4      Co21      O259    2.06996     0   0   0        -0.50467         -0.85410 
      5      Co23      O259    2.11233     0   0   0        -0.43606         -0.73025 