  COHP#    atomMU    atomNU   distance   translation   ICOHP (at) eF    ICOHP (at) eF 
                                                          for spin 1       for spin 2 
      1      Co16      O348    1.87588     0   0   0        -0.45504         -1.47507 
      2      Al51      O260    2.04312     0   0   0        -1.97062         -1.99407 
      3      O260      H116    0.97545     0   0   0        -3.87336         -3.90736 
      4      Co16      O259    2.06996     0   0   0        -0.46155         -0.75311 
      5      Al51      O259    2.11233     0   0   0        -1.78694         -1.80194 